modLoader="kotlinforforge"
loaderVersion = "[5,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "asynclocator"
version = "${version}"
displayName = "Async Locator"
authors = ""
description = '''
'''
#logoFile = ""

[[dependencies.asynclocator]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.asynclocator]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.asynclocator]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "asynclocator.mixins.json"
